name: iOS Build

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build Archive (Unsigned)
        run: |
          xcodebuild archive \
          -project UIKitTestApp.xcodeproj \
          -scheme UIKitTestApp \
          -archivePath build/UIKitTestApp.xcarchive \
          -destination 'generic/platform=iOS' \
          CODE_SIGNING_ALLOWED=NO
          
      - name: Export IPA
        run: |
          xcodebuild -exportArchive \
          -archivePath build/UIKitTestApp.xcarchive \
          -exportOptionsPlist ExportOptions.plist \
          -exportPath build

      - name: Upload IPA Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ios-ipa
          path: build/*.ipa
