name: iOS Build

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build Archive (Unsigned)
        run: |
          xcodebuild archive \
          -project UIKitTestApp.xcodeproj \
          -scheme UIKitTestApp \
          -archivePath build/UIKitTestApp.xcarchive \
          -destination 'generic/platform=iOS' \
          CODE_SIGNING_ALLOWED=NO