name: iOS Build

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Select Xcode version
        run: sudo xcode-select -s /Applications/Xcode.app

      - name: Build iOS App
        run: |
          xcodebuild clean build \
          -project UIKitTestApp.xcodeproj \
          -scheme UIKitTestApp \
          -destination 'platform=iOS Simulator,name=iPhone 15'